import 'dart:typed_data';

// ─────────────────────────────────────────────────────────────────────────────
// OBSCURE — byte-stream deobfuscator for shell-side secrets
// ─────────────────────────────────────────────────────────────────────────────
// All sensitive runtime strings (config endpoint, attribution dev key,
// messaging project number, UA fragments) live in this binary as byte
// arrays — never as plain Dart string literals. This module turns them
// back into UTF-8 strings at runtime.
//
// Key derivation here is FNV-1a + a rolling-rotate stream, NOT the LCG
// approach you may have seen in other shells. Switching algorithm
// changes the post-build binary signature (different mul/add constants,
// different inner-loop ops) — exactly what we want when shipping more
// than one app on the same developer account.
//
// SEED — change for every new project.
//   The seed phrase determines the entire 24-byte key. Two projects with
//   different seeds produce completely different ciphertext for the same
//   plaintext. Re-run the encoder helper any time the seed changes, then
//   paste the regenerated byte arrays into the env/ files.
// ─────────────────────────────────────────────────────────────────────────────

const List<int> _seedBytes = <int>[
  0x44, 0x72, 0x70, 0x5A, 0x6E, 0x32, 0x36, 0x46, 0x6C, 0x6D, // "DrpZn26Flm"
];

const int _fnvOffset = 0x811C9DC5;
const int _fnvPrime = 0x01000193;
const int _rotateMix = 0x9E3779B9;
const int _keyLen = 24;

Uint8List _buildKey() {
  // Stage 1 — FNV-1a fold of the seed into a 32-bit accumulator.
  int acc = _fnvOffset;
  for (final b in _seedBytes) {
    acc = (acc ^ b) & 0xFFFFFFFF;
    acc = (acc * _fnvPrime) & 0xFFFFFFFF;
  }

  // Stage 2 — Rolling 5-bit rotate-left, xor with seed byte, add golden-ratio
  // constant. Drains one key byte per round.
  final out = Uint8List(_keyLen);
  int state = acc;
  for (var i = 0; i < _keyLen; i++) {
    final left = (state << 5) & 0xFFFFFFFF;
    final right = (state >> 27) & 0x1F;
    state = (left | right) & 0xFFFFFFFF;
    state = (state ^ _seedBytes[i % _seedBytes.length]) & 0xFFFFFFFF;
    state = (state + _rotateMix) & 0xFFFFFFFF;
    out[i] = state & 0xFF;
  }
  return out;
}

final Uint8List _streamKey = _buildKey();

/// Decode an obfuscated byte list back into a Dart string.
///
/// The encoder produced the bytes by XOR-ing each plaintext byte against the
/// stream key cyclically; this reverses the same operation. Returns an empty
/// string if [bytes] is empty.
String reveal(List<int> bytes) {
  if (bytes.isEmpty) return '';
  final raw = Uint8List(bytes.length);
  for (var i = 0; i < bytes.length; i++) {
    raw[i] = bytes[i] ^ _streamKey[i % _streamKey.length];
  }
  return String.fromCharCodes(raw);
}

/// Re-encodes a UTF-8 plaintext string into a byte array using the same key.
///
/// Lives here only because the symmetry guarantees the keys match. Call this
/// from a one-off Dart script, copy the printed array into env/, then delete
/// any plaintext copies of the source secret. Never invoke from production
/// code paths.
List<int> hide(String plain) {
  final raw = plain.codeUnits;
  final out = List<int>.filled(raw.length, 0);
  for (var i = 0; i < raw.length; i++) {
    out[i] = raw[i] ^ _streamKey[i % _streamKey.length];
  }
  return out;
}
